name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  echo:
    name: Print Username
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username }}
