name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  echo:
    name: Print Username (job ${{ matrix.chunk }})
    strategy:
      fail-fast: false
      matrix:
        chunk: [0, 1]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username }} ${{ matrix.chunk }}
