name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
env:
  CHUNKS: 4
jobs:
  config:
    runs-on: ubuntu-latest
    name: Define matrix parameters
    outputs:
      MATRIX: ${{ steps.set-matrix.outputs.MATRIX }}
      LAST_INDEX: ${{ steps.set-matrix.outputs.LAST_INDEX }}
    steps:
      # - name: Set Matrix
      #   id: set-matrix
      #   run: |
      #     MATRIX=$(echo '[]' | jq '[range(${{env.CHUNKS}})]')
      #     LAST_INDEX=$(echo $MATRIX | jq 'last')
      #     echo ::set-output name=MATRIX::$(echo $MATRIX)
      #     echo ::set-output name=LAST_INDEX::$(echo $LAST_INDEX)
      - uses: actions/github-script@v6
        id: set-matrix
        with:
          script: |
            core.setOutput('MATRIX', Array.from({ length: process.env.CHUNKS }, (v, i) => i));
            core.setOutput('LAST_INDEX', process.env.CHUNKS - 1);
  echo:
    needs: config
    name: Print Username (job ${{ matrix.chunk }})
    strategy:
      fail-fast: false
      matrix:
        chunk: ${{fromJson(needs.config.outputs.MATRIX)}}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.config.outputs.MATRIX }}
      - run: echo ${{ inputs.username }}
      - run: echo ${{ matrix.chunk }}
      # - run: echo ${{env.CHUNKS}}
      # - run: echo ${{needs.config.outputs.MATRIX}}
      - run: echo ${{needs.config.outputs.MATRIX}} | jq 'last'
      - run: echo ${{needs.config.outputs.LAST_INDEX}}
      - name: not last steps
        if: ${{ matrix.chunk < needs.config.outputs.LAST_INDEX }}
        run: echo 'Not Last step'
      - name: last steps
        if: ${{ matrix.chunk == needs.config.outputs.LAST_INDEX }}
        run: echo 'Last step'
