name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
env:
  PARALLEL: 4
jobs:
  config:
    runs-on: ubuntu-latest
    name: Define matrix parameters
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          echo ::set-output name=matrix::$(echo '[]' | jq '[range(${{env.PARALLEL}})]')
  echo:
    needs: config
    name: Print Username (job ${{ matrix.chunk }})
    strategy:
      fail-fast: false
      matrix:
        chunk: ${{fromJson(needs.config.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username }}
      - run: echo ${{ matrix.chunk }}
      - run: echo ${{env.PARALLEL}}
