name: Unit and Integration Tests

on: push

jobs:
  main:
    runs-on: ubuntu-20.04
    outputs:
      username: ${{ steps.echo.outputs.username }}
    steps:
      - name: echo
        id: echo
        run: echo "::set-output name=username::zohaib-enquizit"

  results:
    needs: main
    uses: zohaib-enquizit/workflow/.github/workflows/echo.yml@main
    with:
      username: zohaib-enquizit

    # runs-on: ubuntu-20.04
    # needs: main
