name: Unit and Integration Tests

on: push

jobs:
  main:
    runs-on: ubuntu-20.04
    outputs:
      username: ${{ steps.echo.outputs.username }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          cache: "yarn"

      - name: echo
        id: echo
        run: echo "::set-output name=username::zohaib-enquizit"

  results:
    uses: zohaib-enquizit/workflow/.github/workflows/echo.yml@main
    with:
      username: zohaib-enquizit

    # runs-on: ubuntu-20.04
    # needs: main
